-- Bedrock weatering survey database project
-- Contriubuters: Andrew Kuhlken, Coden Stark, Luca Viarengo

-- for inserting everything else, this may be a helpful tool: https://simranjitk.github.io/sql-converter/

INSERT INTO Researcher (Name)
VALUES ("Lyman Persico"),
       ("Nick Bader");

INSERT INTO Researcher (Name, GradYear, FirstAdvisor, SecondAdvisor)
VALUES ("Coden Stark", 2024, 1, 2),
       ("Harsh Chopra", 2024, 2, 1),
       ("Cameryn Greenough", 2024, 2, 1),
       ("Megan Driggers", 2023, 2, 1)
       ("Rebecca Patterson", 2025, 2, 1);


INSERT INTO Sample (ID, OutcropID, ResearcherID, Type, Depth, Description, Date, LayerNumber)
VALUES ("RP23-SG6-1", 1, 7, "Rock clast", 54, "Clast from C2 horizon w/ calcium carbonate coating (due to weathering/leeching in modern day soil)", '2023-06-06', 3),
    ("RP23-SG6-2", 1, 7, "Rock clast", 23, "Mostly unweathered Umatilla basalt clast from R horizon", '2023-06-06', 4),
    ("RP23-SG6-3", 1, 7, "Baked soil", -3, "From cooked layer, not quite sure what this represents (could be cooked soil), crumbly, lots of mineral grains", '2023-06-06', 5);


-- join table... don't need?
INSERT INTO SamplePhoto ()
VALUES ;


-- so hard to do...
INSERT INTO SampleChemData (TestNum, SampleID, LabID, Depth, Description, Date, SiO2, TiO2, Al2O3, FeO, MnO, MgO, CaO, Na2O, K2O, P2O5, Sum, LOI, SiO2n, TiO2n, Al2O3n, FeOn, MnOn, MgOn, CaOn, Na2On, K2On, P2O5n, Ni, Cr, Sc, V, Ba, Rb, Sr, Zr, Y, Nb, Ga, Cu, Zn, Pb, La, Ce, Th, Nd, U, SumTr, PrctTr, MinPlusTr, MajPlusTrOx, w_LOI, IfFerric, NiO, Cr2O3, Sc2O3, V2O3, BaO, Rb2O, SrO, ZrO2, Y2O3, Nb2O5, Ga2O3, CuO, ZnO, PbO, La2O3, CeO2, ThO2, Nd2O3, U2O3, SumTrOx, PrctTrOx)
VALUES (1, "HC23-WEH1-1", "GAL-NB-165-1",70, "rock", '2023-08-03',54.83,2.729,13.01,13.5,0.203,2.44,5.99,3.26,1.81,0.801,98.58,1.19,55.61,2.77,13.2,13.7,0.21,2.48,6.08,3.31,1.84,0.81,1,0,33,162,851,55,315,244,53,17.7,24,11,162,8,31,68,6,43,2,2086,0.21,98.79,98.84,100.03,101.53,0.9,0,50.4,238,950.6,59.8,372.9,329.4,66.9,25.3,32.5,14,201.3,9.2,36.4,84.2,6.5,50.2,1.7,2530,0.25);


-- For SG6 only
INSERT INTO StratLayer (OutcropID, LayerNumber, Description, TopDepth, BottomDepth)
VALUES (1, 1, "A-horizon. Frequent fine roots, very slight darkening, greyer in color, less gravel, dominated by sands and silts", 72, 69),
    (1, 2, "C1 horizon. Silty sandy C, rock fragments of basalt up to 3cm in width. Angular, fine to very fine roots.", 69, 60),
    (1, 3, "C2 horizon. Lower boundary is abrupt and irregular, coarse-fragmented horizon with clasts up to 5cm, deposition of CaCO3 rinds on bottom of basalt clasts", 60, 47),
    (1, 4, "Relatively unweathered Umatilla basalt. Fractured, not very vesicular. Max joint distance 20cm in the veritcal direction and horizontal fractures are 1-5cm apart.", 47, 0),
    (1, 5, "'cooked layer,' top of Frenchman Sorings basalt. Surface with white top of layer that did not fizz when HCl was applied. Manganese oxides present. Thin horizontal fractures with bright red streaks of presumably cooked minerals. Upper contact us abrupt and wavy.", 0, -8),
    (1, 6, "Upper contact is smooth and clear. 'pebble layer' verticle fractures spaced every 3-5mm that are filled with yellowish greenis redistributed sillicas or clays. Series of horizontal fractures that are very fine, mm in spacing. Pebbly material is dark brown-dark red in color, little evidence of primary minerals present. Bigger pebbles on bottom of layer, smaller pebbles near top of layer. Lower contact is abrupt and irregular. ", -8, -29),
    (1, 7, "more competant spheroidally weathered vesicular basalt. Vesicles are filled with powdery oxides. Likely Fe and Mn oxides. This basalt is heavily weathered to a purple-ish color.Sugary/powdery crystalline material in vesicles, flaky yellowish powder, red infillings. Silica crust.", -29, -70),
    (1, 8, "abrupt and wavy upper boundary. Model layer, ledge/step former. Vesicular, up to 1cm in size, less weathered, more resistant than overlying layer. Less infillings of orangey material. White material fizzes with HCl, likely accumulation of CaCO3.", -70, -79),
    (1, 9, "more resistant, deeply weathered basalt with lots of colors. Reddish and orange indicating mire intensely weathered between cores of basalt. Less weathered basalt still has vesicles completely filled with material that looks like clays, representing intense weathering of basalt and little primary minerals present.", -79, -100),
    (1, 10, "deeply weathered basalt with more resistant corestone--interiors of corestones behave more like rock and less like sapprolite. Entire layer graded top dowb from more to less weathered. Cores at bottom are darker and less weathered, most vesicles filled . Pervasive vertical and horizontal joints filled with CaCO3 corresponding to its position near modern colluvium. Between corestone: black-green-grey fine-grained matrix, can break apart with fingers, no distrinct basalt clasts. Stage 4 saprolite? Deeply weathered with some primary vesicles present.", -100, -155),
    (1, 11, "More weathered bedrock, 45 cm thick. Slightly vesicular basalt, thuds with hammer. Vesicled filled with reddish or yellowish material. Chemical alteration present. Corestones are 5 to 25 cm wide.", -155, -200),
    (1, 12, "vesicles and CaCO3 decreasing as you go down the layer. Very unweathered. light reddening on fractured surfaces.", -200, -250);




-- Below are insert statments generated by datascraping.py

INSERT INTO Outcrop (Name, Description, Location, 3Dmodel) 
    VALUES ("SG6","Small tributary of Spring Gulch on North Side of Spring Gulch on a south-facing slope. 1st order drainage. Hillslope continuously mantled in thin colluvium with sparse exposures of bedrock. Colluvium ranges in thickness from 30 cm to 80 cm from bottom of site to top. The site is approximately 10 meters from bottom of drainage. Backslope of hillslope; slope shape is linear. Frenchman Springs overlain by Umatilla basalt.",Point(-118.913026, 46.0077),"https://cloud.pix4d.com/dataset/1540228/model?shareToken=b20c98de-6000-41c2-a213-67660ebdbd9c"), 
    ("KID1","Along the Kennewick Main Channel (irrigation canal) in the roadcut (channelcut?). On a northwest facing slope with Pomona, Ice Harbor, and Elephant Mountain basalts. The hillslope below the outcrop is covered in sagebrush and talus slopes of Ice Harbor (?) basalt. In the outcrop, the overlying basalt is likely Ice Harbor, the lower basalt is likely Elephant Mountain, and a soil is present between them.",Point(-119.274435, 46.181069),"https://cloud.pix4d.com/dataset/1555260/model?shareToken=0ed39edc-7a57-420a-a2cb-5b8f9b1d6683"), 
    ("MFQ1","An active quarry south of Milton Freewater, OR. Mapped as a contact between the Umatilla and Frenchman Springs basalts. There's significant modern soil development on top of the Umatilla flow. The site itself is at the north end of the quarry and is found on the west facing slope. The basalt is not very weathered and is largely competent. Beneath the site is a significant slope of talus and other fine sediment.",Point(-118.395846, 45.869212),"https://cloud.pix4d.com/dataset/1544866/model?shareToken=16a8214e-9b75-4b3c-865c-b9372968aa1e"), 
    ("GIC1","Downriver from the Ice Harbor Dam on the east side of the Snake River. Northwest facing hill slope. Solid columnar basalt with significant weathering at surface exposed as a cliff-face. The contact between flows is right above the base of the cliff, although there is a clay-rich layer below the presumed contact that may represent another contact within Ice Harbor flows. The first identified contact appears platy above, with columnar cooked/lithified aggregates below.",Point(-118.913513, 46.241402),"https://cloud.pix4d.com/dataset/1547504/model?shareToken=c8dc2387-3eea-4b96-9c68-524039fb1bb4"), 
    ("GIC2","Downriver from the Ice Harbor Dam, but closer to the dam than GIC1. On the east side of the Snake River. NNW facing hillslope. Outcrop was elevated, at top of slope covered with talus and vegetation. Contact from GIC1 is exposed at about 2 meters above standing point on slope, contact with ash is at about 1.5 meters.",Point(-118.913181, 46.24155),"https://cloud.pix4d.com/dataset/1548806/model?shareToken=5b9ff26c-40f3-4911-9998-0dca47e64161"), 
    ("WC1","Road cut making a WNW hillslope along Webber Canyon road. Modern soil and vegetation above, then overlying basalt (crumbly + unstable fractured), then paleosol with clasts. Basalt below, likely Pomona, is buried in colluvium and angular talus (especially after basalt falls from layer above) with clayey mud below forming a slope towards the road.",Point(-119.457662, 46.185472),"https://cloud.pix4d.com/dataset/1552894/model?shareToken=f3cbe09b-4a2a-4af9-aeae-add5f30da3cd"), 
    ("WC2","Slightly further north than WC1 but along the same roadcut facing WNW. To the left of the site was thick layers of modern carbonate between the modern soil and basalt below. Modern soil with grass and sagebrush is above the outcrop, then crumbly basalt mixed with a finer sediment matrix and roots. Below basalt is a gley colored wavy layer like the smaller area at top of columnar structure layer in WC1. It has clasts and appears to be part of a flame structure maybe. Under the blue is a columnar ped(?) layer before going into Pomona basalt float with finer soil as the matrix. The lowest layer is solid Pomona basalt, and underneath is just talus and finer sediment that slopes down to the road.",Point(-119.457419, 46.185941),"https://cloud.pix4d.com/dataset/1552901/model?shareToken=21005617-a4c3-4d99-9f6b-9184e10156c3"), 
    ("WC3","Opposite hillslope from WC1 and WC2 on the ESE facing hillslope. Slope is mostly covered with colluvium and grass with some exposed Elephant Mountain and Pomona basalts. Site was a contact between EM and Pomona, with both found exposed at the surface of the slope nearby. Apparant soil development between the two flows when colluvium was cleared away.",Point(-119.458592, 46.185901),"https://cloud.pix4d.com/dataset/1554158/model?shareToken=1a9c4780-0dc4-4362-8593-24d196fcfbdd"), 
    ("IHD1","On northwest facing slope on a cliff to the northeast of the Ice Harbor dam and the Indian Monument. Along the Snake River, the outcrop is NE of the Goose Island Cliff (GIC) sites. The cliff itself can be access via a roadgrade that decends from the Indian Monument parking area and consists of cliffs of columnar and more rubbly basalt (the top cliff with a radial structure on southern end that's interpreted to be a lava tube), colluvium, loess, and vegetation. The outcrop is immediately below the top set of columnar basal and is a long vertical trench that reaches down to the basalt below.",Point(-118.8755, 46.246063),"https://cloud.pix4d.com/dataset/1560657/model?shareToken=52b4ff24-1dac-45fe-acc6-7fbe1ae3f63d"), 
    ("SGQ1","Exposed cliffs of columnar Umatilla basalt along entrance road to Spring Gulch, east of the SG sites. Above the cliff is a field with about a meter of loess, modern soil, and grass. It's a southeast facing hill slope where the cliff wall is unstable/separating from base and there's spheroidally rounded talus beneath. The base of the outcrop has been flattened by people for quarrying purposes.",Point(-118.898303, 46.005325),""), 
    ("TC1","Southeast facing hillslope. Contact between Grande Ronde basalt flows (N2 and R2) with a modern soil developed on top. While the contact itself is part of a basalt cliff, the outcrop is part of a larger hillslope. Upslope of the outcrop are basalt columns sticking out of the grass (at least 10m above). The outcrop is at the base of a drainage from the slope above, and the upper surface of the upper basalt tilts downward to the left (toward the drainage). There's a very thin modern soil directly above the upper basalt with lots of grass. Below the top flow is red rubbly vesicular basalt facies. The lower basalt is very vesicular and fractured.",Point(-118.046308, 45.982907),"https://cloud.pix4d.com/dataset/1564700/model?shareToken=9e7d8756-e91d-4b26-92d1-f214257211c2"), 
    ("TC2","An outcrop showing the development of a modern soil on top of the Grande Ronde basalts. It's at a bend on the road with another road diverting off just below. The outcrop is on a west facing hillslope/roadcut with shurbs and grass in a variably thick soil above basalt. The soil had lots of roots and is above spheroidally weathered basalt clasts. Buried in the talus and fine grained weathered basalt is more basalt that is crumbly and more priable(?) than what it's below. The outcrop is about 2 meters above the road surface and is near the top of the sloped surface.",Point(-118.016742, 45.942744),"https://cloud.pix4d.com/dataset/1564758/model?shareToken=a9b84936-4717-463f-a41b-b25e68224b1e"), 
    ("BM1","Basalt cliffs exposed in a roadcut along the road to Jubilee Lake. Down the road from the outlook/pull out where Dylan worked on BM2. It's a south facing hillslope with a contact between the upper Lookingglass Basalt (rubbly and columnar) and the lower Grande Ronde N2 (vesicular and fractured). Between the two basalt flows is a very red layer with core stones and paleosoil. Above the upper Lookingglass basalt is a shallow slope with grass and shrubs. Below the outcrop is a talus pile with basalt clasts of various sizes. The Frenchman Springs basalt is also visible on the same hillslope, exposed near the top of the slope to the right of the outcrop.",Point(-118.046241, 45.775223),"https://cloud.pix4d.com/dataset/1566671/model?shareToken=5a4804b0-423e-4da5-9b06-7f88eb21dfdb"),
    ("WEH1","On old paved road off of Oregon HW 204, the Weston-Elgin Highway. The contact between Grande Ronde N2 (lower) and Lookingglass (upper) is exposed in a roadcut along the highway, but is closer to road level (about 2 meters up) around the corner in the outcrop. Between the two basalt layers is a very red layer with vesicular basalt and red clay-y to more solid material. The Lookingglass is unburied and visible all along the roadcut, but the contact and lower N2 basalt was mostly buried. Below the outcrop is a mix of fine grained sediment and basalt talus. It's a southeast facing hillslope.",Point(-118.119597, 45.787658),"https://cloud.pix4d.com/dataset/1568965/model?shareToken=bab13421-5184-4829-9484-b88aa678391f");


-- Need to fix first column to work with table:
INSERT INTO StratLayer (OutcropID, LayerNumber, Description, TopDepth, BottomDepth)
    VALUES ("KID1",1,"Interior of the Ice Harbor (?) basalt, weathered. Jointed, not vesicular.",300,20),
    ("KID1",2,"Base of Ice Harbor (?) basalt. Platey with horizontal fracturing. Upper boundary is wavey and abrupt.",20,0),
    ("KID1",3,"Cooked sediment below base of Ice Harbor basalt. Upper contact is abrupt and smooth. Sediment is homogenous with no visible aggregation. Grain size is fine grained (silt to clay) with some potential fine sand grains. Color is mostly grey with some occasionally lighter portions.",0,"-7.5"),
    ("KID1",4,"Sediment between Ice Harbor (?) and Elephant Mountain (?) basalts, below cooked sediment. Upper contact is wavey and abrupt. Vertical cracks visible on the surface along the entire layer. Aggregates are present but small (sub-centimeter in width), could be A (?) or B (?) horizon. Grain size is fine grained. Potentially modeled or has larger grains of differing color (fine grained sand).",-7,-37),
    ("KID1",5,"Lowermost layer of sediment above the Elephant Mountain (?) basalt. Upper contact is gradual and smooth. Bt horizon (clay rich) with vertical cracks along height of layer visible from the surface. Blocky to subprismatic aggregates (longer than wide). Aggregates range in size, over cm wide, 3-5 cm tall.",-37,-64),
    ("KID1",6,"Uppermost Elephant Mountain (?) basalt. Platy and heavily vesicular. Upper boundary is smooth and wavey. Horizontally fractured. Mostly competent but some surface crumbled when brushed. The surface of the basalt was red, and the vesicles were mostly empty.  ",-64,-84),
    ("KID1",7,"Interior of Elephant Mountain (?). Upper boundary clear and wavey. Lower boundary not visible. Massive, reddened, vesicular. Vesicles are larger and more prevalent at the top of the layer.",-84,-220),
    ("KID1",8,"Stream channel deposits with all abrupt bounds. Contains heavily weathered vessicular basalt (Elephant Mountain float?) of significantly varied sizes. Lower boundary is with layer 5.",0,-64);

INSERT INTO StratLayer (OutcropID, LayerNumber, Description, TopDepth, BottomDepth)
    VALUES ("MFQ1",1,"criptobiotic crust on outer layer of modern soil. Loess at thickest part of outcrop is >90-45 cm above contact. Cracks from repeated wet-dry cycles. Mostly horizontal cracks, some vertical. Lower boundary is wavy and clear.",90,45),
    ("MFQ1",2,"calcrete without basalt clasts present. Calcrete chunks ranges from 10 cm to 2cm in width. Calcrete clasts are sub-angular, wider than they are tall, suspended in loess matrix. Stage 4 carbonate. Lower boundary is wavy and clear.",45,25),
    ("MFQ1",3,"Basalt clasts coated in CaCO3, relatively unweathered on the inside. Fractured bits of Umatilla flow also suspended in loess matrix. Basalt is brownish red in color. Lower contact is wavy and clear.",25,15),
    ("MFQ1",4,"Basalt clasts become smaller in this layer, 2cm to sub-cm in width. Angular clasts with no vesicles present. CaCO3 and loess matrix more cemented in this layer than overlying layer. CaCO3 is less crumbly and less fractured. CaCO3 is platy and layered across the outcrop. Farther down you go and the closer to the underlying basalt you get, the more layered the platy carbonate becomes. Lower contact is wavy and abrupt. ",15,0),
    ("MFQ1",5,"angular basalt clasts lifted from rest of bedrock by loess and dust collecting in rock fractures. Aeolian material/accretuinary soil development and carbonate precipitating down. More vertical than horizontal fractures. Basalt clasts are 2X8cm rectangular with no vesicles and very unweathered. Thinly layered carbonate/ soil (?) on bottom of clasts. ",0,"-22.5"),
    ("MFQ1",6,"unweathered bedrock with no vesicles or carbonate. Vertical fractures present, few horizontal. Less advanced fracturing as basalt from layer 5. Dark grey/brown. Light iron-banding present. Upper contact is abrupt and wavy.",-25,-200);

INSERT INTO StratLayer (OutcropID, LayerNumber, Description, TopDepth, BottomDepth)
    VALUES ("GIC1",1,"Interior of an Ice Harbor basalt flow (assumed to be Goose Island). Maybe 2.5 to 3.5 meters in thickness. Basalt is non-vesicular with spheroidal weathering. Forms vague columns, vertical fracturing is more obvious and prevalent (at large scales) than horizontal fracturing. It has a lot of lichen on its exposed surfaces and has an oxidized surface that varies in color from red/yellow/greenish grey. It pings when hit with a rock hammer, which suggests the rock is more oxidized than weathered.",400,115),
    ("GIC1",2,"Basalt layer beneath overhang of overlying basalt. It gives variable pings when hit with a rock hammer, suggesting variable intensity in weathering. Highly vesicular consisting of very small vesicles that are slightly larger at top of layer. The very top of the layer, where it meets with the layer above, has a flaky appearance like that of a weathering rind. The layer is red/orange/grey in color, and some of the flaky sections are more red that their surroundings. The upper contact is wavy and abrupt, and the lower contact is irregular and abrupt. The layer isn't present across the entire area but is present within this site. The vesicular basalt (not flaky section) was too hard to easily sample by breaking with a rock hammer.",115,85),
    ("GIC1",3,"Flow bottom breccia? Extremely variable layer with multiple unique features repeated throughout. Consistently platy basalt surrounding angular to spheroidally weathered basalt clasts (7cm tall and wide at middle basalt layer). Highly fractured basalt with some spheroidal weathering. Platy element of the layer is significantly more wavy on the left side of the outcrop. Small vesicles are present in some of the basalt clasts and crumbly bits. The basalt clasts are fiarly consistently darker (red/dark grey) than the crumbly bits. Because of the crumbly bits, the layer has more horizontal than vertical fracturing.",85,43),
    ("GIC1",4,"Repeated layers of thin fractured basalt (horizontal and platy) and blockier basalt layers. Color is more white in the blocky layer, more red in the platy layer. The platy layer is very crumbly and hard to remove as a solid chunk. The lowest element of the layer is solid blocky basalt with spheroidal weathering. The blocky layers appear more like basalt at the base, but look more like concrete in layers above (vesicular, 4cm basalt on the left side of the site, smaller on the right). Upper bound is abrupt and wavy, lower bound is clear and wavy.",43,18),
    ("GIC1",5,"Lightly weathered 15-30cm between vertical fractures. Lots of tiny vesicles. Sub-angular basalt clasts. Some white coating on basalt. Basalt in this layer varies in color from light grey to dark grey/brown. Lower boundary is clear and wavy.",18,0),
    ("GIC1",6,"Fine grained red sediment at very top of layer right at the contact. Large Prismatic aggregates that range in color from dark grey to red. 25cm in length, 10 cm in width. Some are significantly smaller down to a couple cm and get larger towards the right end of the outcrop. These peds are strongly columnar.",0,-39),
    ("GIC1",7,"very red and besicular basalt with light yellow-white streaks on some faces. More vertical fractures than horizontal. Carbonate precipitation/accumulation. Manganese and iron oxides present. Moderately to loghtly weathered overall in this layer. ",-39,-54),
    ("GIC1",8,"pebbly layer, some larger weathered angular clasts in a fine grained weathered basalt matrix mixed with modern sediment/dirt accumulation. Easily breakeble, not very competent. More modern dirt/soil(?) accumulation on left side of outcrop.",-54,-62),
    ("GIC1",9,"very vesicular basalt that is moderately weathered. Light grey in color with some red. Vesicles are larger at the top of the layer but generally small-moderately sized, <2.5 cm in width. More vertical than horizontal fractures. ",-62,-76),
    ("GIC1",10,"minutely layered clays with small basalt fragments at top which are angular and sparse. Outer layer is more brown and clay-rich. Once scraped away on inner, a more dense layer was revealed. Thin white bands within layer, possibly clay or condensed ash, can scrape with a trowel but dense. More horizontal than vertical cracks. Overall kind of blocky texture. Upper boundary is abrupt and smooth, lower boundary is also abrupt and smooth.",-76,-88),
    ("GIC1",11,"Vesicular basalt, bottom flow, likely martindale. More vesicles at the top than at the bottom of exposed basalt. Lighter grey at the top. No vesicles are filled. Red and purpley oxides on rock races, likely iron and manganese oxides. Moderately weathered variably in fractures and am able to dig the basalt out with a trowel, especially in areas where fine-grained white material is present. The whole layer is weathered at the surface and able to be dug out with a trowel, down to the bottom of the outcrop. STill slightly vesicular at the bottom but less-so than the top. ",-88,-143);

INSERT INTO StratLayer (OutcropID, LayerNumber, Description, TopDepth, BottomDepth)
    VALUES ("GIC2",1,"More solid basalt, some spheroidally weathered columns. White material precipitating down, likely modern CaCO3. lLeast weathered rocks exposed in outcrop. Suspected Goose Island flow above upper Martindale (Indian monument) overlying lower Martindale. No vesicles present. Overall color is red to dark grey/brown. Not very weathered, very pingy when hit with a rock hammer. Bottom contact is clear and smooth. ",250,52),
    ("GIC2",2,"Platy layer, more horizontal than vertical fractures, brown/dark grey, white material accumulating in the joints, as well as modern brown sediment. Not very vesicular from what we can see. Potential flow bottom breccia? Bottom contact is clear to gradual, variable across contact, and wavy. ",52,37),
    ("GIC2",3,"Basalt clasts have similar fracturing pattern, still slightly platy with lots of tiny vesicles that are more squished at the bottom of the layer. Variable in size. Variable degrees of weathering throughout layer. Mre vertical fractures in this layer than overlying layer. Color is dark grey to dark brown, some light-brown to yellowish oxidation on some faces in this layer. Some crumbly basalt in middle of layer. SOme vesicles filled with yellow material. Pahoehoe texture on bottom part of layer.",37,0),
    ("GIC2",4,"The contact! Light grey at the top, grey-blueish in the middle which grades down to red oxides at the bottom. Very vesicular, looks like cooked, oxidezed soil. Below the contact is the columnar peds/aggregates which are dark grey to black and covered in yellow material/secondary minerals. Right side of outcrop their structure becomes blockier and less columnar, widths become more equant. Some very crumbly white layer/material. present. Within the aggregated are large, suspended vesicular basalt clasts ripped up from underlying flowtop. Clasts are sub-angular to rounded. Some more vesicular than others. Some vesicles in selected basalt clasts filled with same yellow material covering aggregates. ",0,-51),
    ("GIC2",5,"reddened vesicular basalt below aggregates. Lots of vesicles ranging in size. Some fractures, more vertical than horiizontal. Vesicles coated with white and yellow secondary clays and oxides. Plagioclase crystals present. Very fine grained basalt with few phenocrysts. Not very weathered, still pretty resistant. Blasted/weathered primary minerals that were weathered to a different mineral.",-51,-82),
    ("GIC2",6,"Upper contact is wavy and abrupt, lower contact is irregular and abrupt. White super fine grained solidified/lightly lithified ash. Top of ash has embedded vesicular, unweathered but broken basalt clasts with unfilled vesicles. Pebbly texture on top. Texture becomes smoother halfway through layer. Right side of outcrop is an ash overhang where lower boundary extends beneath surface, greater than -185cm. Tiny angular ripped up basalt clasts embedded within ash layer. ",-82,-145),
    ("GIC2",7,"upper contact is irregular and abrupt, lower contact is irregular and abrupt. Vesicular, lots of yellow and red oxides. Some vesicles are filled with secondary yellow and white minerals. Still resistant, more vertical than horizontal fractures. Modern yellow powdery material on the outside/underside of ash layer.",-145,-185);

INSERT INTO StratLayer (OutcropID, LayerNumber, Description, TopDepth, BottomDepth)
    VALUES ("WC1",1,"Suspected elephant mountain flow, not super weathered but highly fractured, basically brecciated and not vesicular. Some iron banding but other than than I don't see much secondary mineral accumulation/precipitation. Very thin modern soil at very top where plants are growing. Modern dirt/loess covering most of upper rock faces that we could not reach to clean off. Lower boundary is wavy and clear. ",390,90),
    ("WC1",2,"Fractured flow bottom of potential elephant mountain. pervasive vertical and horizontal fractures, more horizontal than vertical. Lower boundary at outcrop is abrupt and clear. No vesicles, dark grey, brown, red, greenish in color. Few oxides, no secondary mineralization, pretty unweathered appearance overall. Very pingy when hit with a rock hammer. ",90,0),
    ("WC1",3,"Lower boundary is abrupt and irregular. Upper part of layer there are columnar aggregates/structures with small angular and unweathered basalt clasts in them. Blueish grey in color with light yellow/orange mineralization on the outside. white material also present in joints/cracks. Large vesicular clasts suspended within this paleosol. Clasts range from 10cm to 38cm in diameter. Soil development present beneath clasts and on sides of them, likely floating due to loess and dust accumulating in joints and pushing chunks of vesicular basalt from upper suspected pomona flow up and away from bedrock. Most floating clasts are angular, some are rounded and less vesicular. Clasts towards upper layer have same mineral coating and coloring as the structures. ",0,-68),
    ("WC1",4,"Vesicular flowtop of suspected pomona flow. fractured but not as fractured as elephant mountain. Vesicles are bigger towards the top. Blocky fractures, equal amount of vertical and horizontal fractures. Little secondary mineral accumulation, some dark yellow mionerals filling vesicles, evidence of Diagenetic processes. Some iron banding present. Most vesicles unfilled, but a lot of them have a yellow coating. Potentionally common opal? ",-68,-100);

INSERT INTO StratLayer (OutcropID, LayerNumber, Description, TopDepth, BottomDepth)
    VALUES ("WC2",1,"Modern soil seen from a distance, could not get that close to it because of its position on a steep unstable slope. It is dark brown in color and abou a foot deep. Can't see any distinct horizons from where I'm standing. ",200,168),
    ("WC2",2,"Suspected elephant mountain flow that is auto-brecciated and highly fractured, very vesicular, and fragmanets are very angular. Color is dark grey to dark brown. Upper boundary is smooth and clear while lower boundary is abrupt and irregular. Pahoehoe present in this layer indicating it is a flowtop",168,30),
    ("WC2",3,"Right side of boundary exposes evenly spaced columnar structures with yellowish whitish mineral accumulation, columnar structure potentially from how it cooled. Overall color of this layer is a blue-grey gley. Wen broken off the columns behave more like mildly weathered basalt than soil. Columnar structure stop 12cm down before transitioning into a blocky texture. Just like blue section from WC1. Large sub-rounded vesicular clasts suspended within blueish layer, ranging from 12cm to 22cm in width. Potentially some kind of rip-up from top of underlying pomona flow. ",30,0),
    ("WC2",4,"Upper contact is wavy and abrupt. Arguably gradual in some sports along the outcrop. Structure of blueish sediments is more elongated and prismatic with more white, yellow, greenish mineral precipitation on it. Pervasive vertical and horizontal fractures, more vertical than horizontal. At he bottom of the layer there are a couple of large, lifted, angular vesicular pieces of pomiona. Lower contact is wavy and gradual. More fractured at base of this layer.",0,-45),
    ("WC2",5,"Transitional layer. More frequent large vesicular clasts of pomona, 18 to 40cm in width. Structures in this layer are smaller, more blocky, less columnar than overlying layer. still very fractured. more white mineral coating these structures than overlying layer and less gley color at the surface than overlying layer. Lower contact is gradual and wavy.",45,-70),
    ("WC2",6,"More vesicular basalt clasts that are lifted. pretty fine-grained wettish sediment between clasts. yellow, white, and light brown overall in color. The white material specifically veins throughout the profile, potentially carbonate from being near the surface. Occasional black and yellow spots of material within this layer. This clay-like material boundaries all the lifted clasts in this layer. less weathered vesicular basalt clasts, angular, found occasionally within clay material. ",70,-105),
    ("WC2",7,"Pomona basalt, pervasively fractured bith vertically and horizontally. Not very vesicular, some modern carbinate veins on outermost basalt. Similar amount of vertical and horizontal fractures. Basalt is fractured but otherwise appears to be pretty unweathered. Light to dark grey in color. Inconsistently vesicular lower down in exposed pomona. ",105,-200);

INSERT INTO StratLayer (OutcropID, LayerNumber, Description, TopDepth, BottomDepth)
    VALUES ("WC3",1,"Modern soil on top of crumbly Elephant Mountain basalt. No obvious soil horizons, lots of grass growing. most visible soil covered with cryptobiotic crust. Fine grained, likely loess dominated. slopes downward, not a cliff so it's hard to gauge actual depth. Lower boundary appears to be wavy and clear but it's hard to tell because of slope and instability of the layers on either side of the boundary.",100,90),
    ("WC3",2,"Highly fractured, more horizontally than vertically, non-vesicular basalt, expected to be Elephant Mountain based on Rockd map. Pockets/areas of more platy to blocky structure distributed throughout layer. Surface has some dark blue to orange oxidation but the exposed surface of the basalt is mostly tan to grey/blue. Largest solid basalt pieces (non-fractured) are a max of 24cm with most being around 10cm. Filling/coating the inside of the fractures are oxides (green, purple/blue, orange) that have accumulated. top half of layer was not buried and has some evidence of spheroidal weathering. lower half of layer was partially buried and is more angular. ",90,0),
    ("WC3",3,"Upper boundary abrupt and wavy. lower boundary is gradual and wavy. Pebbly structure of dark grey/blue color. Orange to yellow material found inbetween every pebble structure near the top of the layer close to the contact (where there's more pebbles that are crumbly/easy to remove). Yellow material lower in the layer is confined to vertical veins. between the veins, the bluish material appears more columnar than above, has no orange/yellow between structures, but still crumbles at surface. At the contact itself, there's some modern soil.",0,-40),
    ("WC3",4,"Mostly the same as the layer above. Slightly lighter in color (lighter grey to slightly gley color) with a more cohesive structure (no columnar/pebbly structure that crumbles easily). Less obvious vertical fractures. very fine grained. Lacks the orange/yellow material that was abundant in the layer above. Lower boundary is abrupt and wavy. Feels more like a soil than layer above, feels clay-like when scraped with a trowel. Has some larger chunks of more solid basalt saprolite.",-40,"-52.5"),
    ("WC3",5,"Depth varies throughout outcrop, depends on highest basalt from Pomona layer below. Found right above the very top of the bedrock and below layers 3 and 4 that look more like soil. Lower boundary is abrupt and wavy where it meets with basalt. Very base of layer has green, yellow, tan very fine grained minerals at surface of basalt. Lower half also has weathered basalt clasts covered with clay, non-vesicular. More crumbly appearance at top with larger seeming grains (although they disintigrate with force). Top is mostly dark grey with white streaks (crumbles to almost salt + pepper appearance). Behaves more like a soil than overlying saprolite.","-52.5",-67),
    ("WC3",6,"Vesicular basalt, suspected Pomona. Some upper vesicles coated with orange and white material. Surface of the dug out top of flow appears tan to white in color. Vertical faces  that were not buried are more reddish in color, vary from pink to red/orange. Top is fractured with variable ping when hit with rock hammer (very top has dull thud while base of exposed Pomona in scan had good ping), suggests varied degrees of weathering throughout basalt. Some parts of the top on the left have clay material at surface that can be scratched off with trowel.",-67,-400);

INSERT INTO StratLayer (OutcropID, LayerNumber, Description, TopDepth, BottomDepth)
    VALUES ("IHD1",1,"Columnar basalt that becomes less obviously structured higher in the layer. Bluish grey in color. Platy at the lower boundary with some clasts detaching and being mostly in place but suspended in fine grained sediment. Top surfaces with infrequent fractures, covered with lichen, spheroidally weathered.",400,0),
    ("IHD1",2,"Upper boundary is clear and wavy, lower boundary is clear and wavy. Characterized by red color in sediment between basalt clasts. Basalt is spheroidally weathered with a dike present cutting through the left of the layer (and the layer below). The red sediment layer is pebbly with some larger weathered basalt clasts. Some of the sediment is grey in color. Rounded basalt clasts range from about 8 to 11 cm in width. White at bottom of clasts likely to be modern carbonates. ",0,-20),
    ("IHD1",3,"It's almost a shelf-forming layer, where the layer covers more area vertically than horizontally. Characterized by white, stratified layer within the basalt (carbonate? ash?). Basalt is dark blue in color with some limited red oxidation. More 'solid'? basalt. Very vesicular with yellow mineral filling vesicles. The surface of the basalt is uneven. Has a glassy look on fresh surface, massive, nonfractured. ",-20,-25),
    ("IHD1",4,"Characterized by yellow sediment layer visible to the left of the dike. While the yellow is present in the layer above, it's only visible at the surface through layer 4. The yellow sediment is less fine grained than the red sediment, and while it crumbles, there's some larger grains that don't break apart. Yellow sediment also had red grains of varying sizes (maybe chunks of weathered basalt). There's also vesicular basalt like the layer above that's present through the upper 3/4th-ish of the layer. Base of layer is made up of vent facies, very vesicular basalt to fine grained bedrock scoria. The scoria had yellow sediment/mineral at the surface.",-25,-60),
    ("IHD1",5,"Partially shelf forming scoria. Different texture than the massive bedrock scoria from the layer above. Surface of the rock is very light colored (white to tan) about 10 cm below the top of the layer. Above that point is slightly darker (light grey) and more platy. The whole layer has a very dark interior of scoria with vesicular grains visible under hand lens. No obvious fractures. The base of the scoria grades into a dark grey clay (the color change is abrupt but the change in texture is gradual). Upper boundary is abrupt and smooth. Lower boundary is gradual and smooth.",-60,-90),
    ("IHD1",6,"Grey to gley colored clay rich layer. Uniform color through most of the layer (with the exception of red clast) and easy to scrape with trowel. The clast in the layer was below the surface/completely buried in grey sediment and is rust red, about 7cm in length. It's mostly fine grained/clay with the exception of some larger resistant grains. The lower boundary is gradual and clear.",-90,-130),
    ("IHD1",7,"Upper boundary gradual. Under the surface is light colored. Sediment is fine grained, but the white colored material is coarser grained than the gley colored material above. The layer has areas of beige, light/dark grey, and greenish colors that grade into each other. Some white spots are harder/more solid, maybe CaCO3 (didn't test fizz). Harder white grains are about a cm in width and are sparce. The layer also forms a shelf, and the surface of the shelf has fewer white spots but more lighter grey spots that are less solid.",-130,-173),
    ("IHD1",8,"Ash layer. Upper boundary diffuse and wavy. Made up of white ashy material with beige bands crossing each other within the white layer. The white material also has roots in it, could be modern. There's dark red spots present throughout the layer that could be oxidized angular basalt. The white ash is mildly stratified. Moving down the layer, the color changes from majority beige to majority white. More common lower in the layer are dark stringers of maybe basalt scoria ash. These stringers are about a cm in width and are horizontal. They're more soild than the surrounding ash and cannot easily be dug with a trowel.",-173,-208),
    ("IHD1",9,"Vesicular basalt at the top of the lower unit. Super vesicular, fairly small vesicles (sub cm) but very common. Some of the vesicles are coated in greenish/yellow material on the inside. Super pingy when hit with rock hammer. Fractured both horizontally and vertically. Overall color is a light grey but there's also dark blue oxides and light blue precipitated minerals in vesicles. The top of the unit forms a shelf, but it's very fractured and uneven.",-208,-241),
    ("IHD1",10,"Upper boundary is gradual and wavy. Layer is same basalt as above (lower unit) and has consistent horizontal and vertical fractures. The main difference from the layer above is the vesicles, which are larger and less frequent as we move further down the layer. Vesicles get up to about 2cm.",-241,-300);

INSERT INTO StratLayer (OutcropID, LayerNumber, Description, TopDepth, BottomDepth)
    VALUES ("SGQ1",1,"A' soil horizon with grass above. Fine grained with visible sub-cm sized aggregates found around/attached to roots. Because we are on a slope towards the cliff, the sample was taken from a higher elevation and further back on the slope.",85,70),
    ("SGQ1",2,"Upper and lower boundaries are gradual and smooth. Bw horizon (weak/weathered). Fewer roots than above. Less abundant but slightly larger aggregates (still sub-cm, 1/2 cm at the largest) groups around roots. Loess/tan color, but slightly lighter/more white than the A horizon above.",70,48),
    ("SGQ1",3,"Bk horizon, lowest horizon of the soil above basalt. Lighter in color than soil above. Harder to dig out, so more firm/concreted. Roots less common but still prevalent. Occasional aggregates around roots, larger than above (1 to 2 1/2 cm in width). Lower boundary abrupt and wavy. No difference in grain size from the layers above. May have some cm size carbonate clasts at the very base of the layer.",48,0),
    ("SGQ1",4,"Unweathered Umatilla basalt, mostly exposed at the surface due to human quarry activities. From the top, appears like a basalt breccia with carbonate matrix. No carbonate at the top, but abundant below clasts and on sides of some. Basalt clasts are mostly angular but with some more rounded clasts. Very surface of basalt clasts has some dark blue oxides and almost occasionally pitted surface appearance but the interior is dark grey, unweathered, and nonvesicular. Going down the cliff, there's more unweathered basalt with a variety of basalt facies present.",0,-654);

INSERT INTO StratLayer (OutcropID, LayerNumber, Description, TopDepth, BottomDepth)
    VALUES ("TC1",1,"(+)1.5m to contact overlying basalt, vertically fractured.Kind of columnar in how it fractures. Sparse vesicles towards bottom of flow, some are squished. All are sub-cm in width. Some spheroidically weathered clasts exposed out of surface/top of flow. Overall color is dark brown, some greys and mild oxidation. Lower boundary is abrupt and wave. More horizontal/ platy fracturing towards bottom of contact",150,0),
    ("TC1",2,"0 to (-112) cm upper layer is very vescicular basalt, borederline scoria. Basalt is very red and some vesicles are filled with yellow and white minerals that also fill fractures. Vesicles gradually increase in size and quantity throughout the upper layer. The whoile layer is highly fractured.Yellow/white materials prevelant on the right side of the outcrop. No soil develoipment. Large clasts of vesicular basalt that are less oxidized and less weathered than surrounding red basalt. Layer grades down from being mostly grey to mostly red in color. Some dark red/ purple oxides lower in layer",0,-112),
    ("TC1",3,"(-) 112 to > 300cm. Fractured, vesicular lower basalt. Likely R2 flow of Grande Ronde. Very vesicular at top, more competent and less fractures starting around a meter down. Upper layer is crumbly with vesicles ranging in size. Same amount of vesicles as layer 2 but more vesicular than Layer 1. Equal amount of vertical and horizontal fractures. Overall this layer is much less red and vesicles were unfilled but some were coated with yellow/green mineralization.",-112,-300);

INSERT INTO StratLayer (OutcropID, LayerNumber, Description, TopDepth, BottomDepth)
    VALUES ("TC2",1,"A' soil horizon? Very fine grained soil, dominated by loess. the layer has a lot of roots. ped structures are present clumped around roots, small and angular structures. It's darker than the soil layers below.",28,23),
    ("TC2",2,"Fine grained modern soil with consitituent sediment coming from transported loess and weathered basalt the soil developed on top of. Average grain size is larger than layer above due to presence of weathered basalt. Roots present but slightly less common than the layer above. Less cohesive than layers above and below. Upper and lower boundaries are wavy and clear. Peds are more prevalent than the layer above, but are a wider variety of sizes (both larger and smaller than above).",23,13),
    ("TC2",3,"Coarsest grained layer of the modern soil, still a mix of loess and weathered basalt, but more basalt than above. fewest number of roots, but they're still present. Fewer and smaller peds, but they're still blocky and found around roots. Has charcoal of varying sizes (up to >10cm) at base of layer.",13,0),
    ("TC2",4,"Very fractured, spheroidally weathered basalt. Spheres are vesicular, but nothing else in the layer (rinds, fractured areas) is. Vesicles are unfilled. Kind of pingy when hit with a rock hammer, but some of the dampening might be because the layer itself isn't very soild. There appears to be little oxidation or secondary mineralization on the surface of the basalt. The basalt is mostly light grey in color, but there's some orange and black minerals on the outer surface. The entire surface appears fractured, though the fractures are equally horizontal and vertical. The upper boundary is wavy and abrupt. The lower boundary is wavy and clear.",0,-50),
    ("TC2",5,"Super vesicular, rubbly + crumbly basalt. Dark blue manganese oxides present, though the majority of the layer, when dry, is a similar light grey as the layer above. There's some yellow/orange coloring at the surface. Most vesicles at the surface are empty (almost no filling or coating), but very few have orangy mineral within them. The vesicular-ness of the layer varies as there's pockets of bigger/more prevalent vesicles in areas higher up in the layer. It's crumbly, though the surface exposed at the outcrop is more solid than the material of similar appearance that was removed. The less vesicular areas were often more crumbly. The lower boundary is wavy and clear. Some of the interior vesicles are filled. To the left of the vesicular/rubbly majority of the layer, there's a more massive, horizontally fractured basalt pieces.",-50,-105),
    ("TC2",6,"Reddened layer between basalt flows, likely the same contact between Grande Ronde N2 and R2 that was identified and described at TC1. Wavy streaks (nearly cm in width) of red appear at the surface of the layer, and are more often horizontal than vertical. Overall, the layer is more soild and harder to remove than the rubble above. The red in the streaks appeared to be clay or at least extremely fine grained. ",-105,-130);

INSERT INTO StratLayer (OutcropID, LayerNumber, Description, TopDepth, BottomDepth)
    VALUES ("BM1",1,"Lookingglass Basalt. Rubbly closer to the contact (up to 10-20cm above), but more resistant and columnar above that. The contact between the basalt and the red layer below is irregular and abrupt. Columnar portion is largely nonvesicular, and the more rubbly portion is significantly less vesicular than basalt layer below. The surface is grey/green/blue in color with some sections of reddening. Closer to the contact, the reddening of the surface appears more red while it appears more purple moving up and away from the contact. It's spheroifally weathered, massive, and has more vertical than horizontal fractures.",300,0),
    ("BM1",2,"Very red cooked top of soil developed on top of the N2 basalt. Non-vesicular, but fractured, crumbly, and very angular. It's super fine grained and gets blockier/more resistant/massive closer to the contact with the overlying Lookingglass basalt. Within the blocky structures, there's some black flecks at the surface, both angular and rounded but flush with surface, mm scale. There's also white/yellow oxides at the surface. The lower bound is clear and gradual. The uppermost portion of the layer looks similar to the soil + basalt contact at WC1 and WC2.",0,-10),
    ("BM1",3,"Very large and reddened basalt core stone, spheroidally weathered with concentric rinds extending out throughout the layer. The surface is reddened with yellow minerals in the vesicles. surface is bluish, with areas that vary from orange/red to red/purple in a streaky pattern. There's some green at the surface in sections. the center of the core is very vesicular, but it becomes less obvious in the concentric layers moving out. Vesicles are of a variety of sizes and frequencies. Some of the interior vesicles are coated with white. Beneath the middle of the corestone, the concentric rinds appear more red/orange and crumbly/finer grained. Most of the basalt in the layer gives a dull ping when struck with rock hammer.",-10,-121),
    ("BM1",4,"Grey vesicular basalt. Upper boundary clear and gradual. The bottom of the layer above is also basalt, very similar in color and texture, but has a platy structure. Highly fractured but no obvious preferred orientation (horizonal, vertical, and diagonal). Some of the larger fractures are filled with a grey material that's more red higher in the layer and more blue lower in the layer. Largest fracture is horizontal, about 50cm below the upper boundary of the layer. On the outcrop, the filled fractures get up to about 3cm in width, but to the left, some are >10cm. Vesicles appear empty at surface. More oxides on the surface of the basalt around the fractures (red, green/yellow).",-121,-300),
    ("BM1",5,"Same elevation and location in the strat column as the top of Layer 3. Resistant and more vertical, probably cooked paleosol. Very red, though slightly more grey/less vibrant than the layers below. Pencil-like structures at the top, with 1-3 cm between vertical fractures. There's black and yellow oxides on the surface. ",0,-18),
    ("BM1",6,"red material, pebbly but resistant (the surface crumbles). The surface crumbles when hit and fractures finely, making it hard to sample. Pebbles aren't original basalt, they're more rust red in color and glossy, non-vesicular. very fine grained. Maybe baked oxidized soil.",-18,-40),
    ("BM1",7,"potentially weathered C horizon based on grain size, location, and texture. Probably not because the grains don't look like basalt, look like the grains above as they're red, fine grained, resistant, smooth, and shiny. Lots of yellow mineral like the layer above. Resistant but crumbles into pebble sized clasts/chunks when struck. Coarser grained pebbles than the layer above.",-40,-47);

INSERT INTO StratLayer (OutcropID, LayerNumber, Description, TopDepth, BottomDepth)
    VALUES ("WEH1",1,"Lookingglass Basalt. Upper 3/4ths of the layer is platy with abundant horizontal fractures and less common vertical fractures that have between ~30 to ~5 cm between them. The lower portion is rubbly in appearance from jointing. The surface of the basalt is a modest brown/red color (along fractured surfaces), and the interior looks unweathered blue/black. There's pockets of small flattened vesicles near the contact of variable size, mostly sub cm. THe basalt is mostly angular. Right above the contact with the lower layer is a darker color, closer to black. It follows the red layer, so it's abrupt and wavy.",100,0),
    ("WEH1",2,"Very top of the reddened sediment(?) layer without any vesicular basalt clasts. Variable thickness throughout layer. Lower boundary is clear and wavy. The layer consists of fine grained red sediment. Some areas are vertically fractured, but only where the material is more resistant/platy and less like wet clay. In the platy areas, fractures are coated with black oxide material. ",0,-4),
    ("WEH1",3,"Very vesicular basalt cores with red material like layer above acting as a matrix and filling larger fractures. Basalt clasts at the top are smaller (~10 cm) and more reddened at the surface. Over the entire layer, vesicles trend towards being smaller at the top, larger when lower in layer. Some of the vesicles at the top are also filled with the red material, but most are either completely empty or coated with yellow. Color varies from red/purple grey to yellow grey depending on the size of the basalt clast and its depth in the layer. Bottom boundary is wavy and clear with the red sediment grading into a light grey over about 3 cm. ",-4,-70),
    ("WEH1",4,"Highly vesicular basalt, similar in appearance to some of the clasts above. variable ping throughout layer, but more pingy moving down. Grey/purple to grey/red at the surface, purple associated with more vesicular areas and red more common lower in the layer. Varied resistance, lower in layer is more resistant, surface of the upper crumbles when struck with hammer. The basalt is mostly blocky in appearance. Vesicles vary in size and abundance, but largest get up to 3cm.",-70,-300),
    ("WEH1",5,"In the separate cleaned outcrop to the left, where the top layer of red below contact is larger. Even the layer below has fewer and smaller basalt clasts (up to 20cm). The top reddened layer appears like soil aggregates (2-3 cm across) and blocky. More grey/purple than red at the top. Clayey. Top 2 cm or two appear more indurated, potentially cooked by the overlying Lookingglass flow. ",0,-15);